# pull official base image
FROM node:17-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY server/package.json ./
COPY server/package-lock.json ./
RUN npm install --silent
RUN npm install -g typescript --silent
# RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY server/. ./

# start app
CMD ["npm", "start"]

# For development
# ENTRYPOINT ["tail"]
# CMD ["-f","/dev/null"]