version: '3.1'

services:

  bmg-server:
    build:
      context: .
      dockerfile: "Dockerfile.server"
    image: "bmg-server:dev"
    container_name: "bmg-server"
    ports:
      - "8080:80"
    volumes:
      - ./server:/app

  bmg-client:
    build:
      context: .
      dockerfile: "Dockerfile.client"
    image: "bmg-client:dev"
    container_name: "bmg-client"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      