version: '3.1'

services:

  bmg-server:
    build:
      context: .
      dockerfile: "Dockerfile.server"
    image: "bmg-server:dev"
    container_name: "bmg-server"
    ports:
      - "8080:8080"
    environment: 
      BOARD_HEIGHT: 20
      BOARD_WIDTH: 20

  bmg-client:
    build:
      context: .
      dockerfile: "Dockerfile.client"
    image: "bmg-client:dev"
    container_name: "bmg-client"
    ports:
      - "3000:3000"
      